use database snowflake_sample_data;
desc table tpcds_sf100tcl.store_sales;

select count(*)
from TPCDS_SF100TCL.STORE_SALES;

Use WAREHOUSE COMPUTE_WH;
USE DATABASE SNOWFLAKE_LEARNING_DB;
CREATE SCHEMA IF NOT EXISTS BRONZE;
CREATE OR REPLACE TABLE BRONZE.STORE_SALES_RAW AS 
SELECT * 
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.STORE_SALES
LIMIT 5000000000; 

SELECT COUNT(*) FROM BRONZE.STORE_SALES_RAW;

DESC TABLE BRONZE.STORE_SALES_RAW;
SELECT
    COUNT(*) AS total_row,
    COUNT(ss_sales_price) AS non_null_sales_price
FROM BRONZE.STORE_SALES_RAW;
SELECT MIN(ss_sold_date_sk),MAX(ss_sold_date_sk)
FROM BRONZE.STORE_SALES_RAW;


